server:
  port: 9001
#  servlet:
#    context-path: /spring
spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://172.16.8.105:3306/tvmall?useUnicode=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.yunhe.java.pojo
info:
  manage: 这个服务是电视商城用户的提供者
eureka:
  client:
    service-url:
      defaultZone: http://172.16.8.105:8083/eureka
